# Swagger UI configuration
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.validator-url=none
#
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
#
#
quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install.npm-version=10.2.3
quarkus.quinoa.enable-spa-routing=true
#
#
# liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.validate-on-migrate=false
quarkus.liquibase.default-schema-name=contribution_management
#
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=mathisEnzo21*
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres.digiciel.local:5432/postgresdb?currentSchema=contribution_management
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://keycloak-db-postgresql.postgres.svc.cluster.local:5432/postgresdb?currentSchema=contribution_management
# 
# Container image configuration
quarkus.container-image.group=digiciel
quarkus.container-image.name=contribution-tracker
quarkus.container-image.username=jmtamga
quarkus.container-image.password=mathisEnzo21*
quarkus.kubernetes.generate-image-pull-secret=true
quarkus.container-image.tag=latest
quarkus.container-image.registry=gitea.digiciel.local
quarkus.container-image.push=true
quarkus.container-image.build=true
quarkus.container-image.builder=jib
quarkus.kubernetes.namespace=contribution-tracker
quarkus.kubernetes.output-directory=../k8s
#
quarkus.quinoa.ignored-path-prefixes=/api,/actuator,/swagger-ui,/openapi,/q,/q/health,/q/metrics,/q/openapi
